### ISSUE TITLE
Unexpected closing quote when single quote within interpolated string

### ISSUE THREAD

**Issue by jeffchan** [decaffeinate/decaffeinate-parser#2]
Somewhat of an edge case:
```
a = "#{b}'a'')"
```
results in
```
Error: unexpected closing quote before the end of the string
```

**Comment by eventualbuddha** [comment]
Yep, this is due to my [hacky code](https://github.com/decaffeinate/decaffeinate-parser/blob/e1f5fc935168a40d318814cafb7d5f0b6e0965c1/src/util/parseLiteral.js#L159-L171) that attempts to figure out whether something is a literal part of a string interpolation (i.e. `'a''` in `"#{b}'a'')") or an interpolated string (i.e. `'a'` in `"#{'a'}"`).

Man, I hate CoffeeScript.

**Comment by Eden-Sun** [comment]
I think `a = "#{b}'a'')"` and `"#{'a'}"`  are closed unless you wanna solve `"#{"a"}"` ,  any possibilities to write that ?

**Comment by madskonradsen** [comment]
Seems to have been fixed too :)

**Comment by alangpierce** [comment]
Thanks for pointing that out! Closing.
